<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ComposeUnityTargetFramework Condition="'$(ComposeUnityTargetFramework)' == ''">net9.0</ComposeUnityTargetFramework>
        <TargetFramework>$(ComposeUnityTargetFramework)</TargetFramework>
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>false</SelfContained>
        <DebugType>none</DebugType>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>steamcmd</AssemblyName>
        <RootNamespace>ComposeUnity.SteamCmd</RootNamespace>
    </PropertyGroup>
</Project>
