name: Docker

on:
    push:
        branches:
            - "main"
        paths:
            - "linux/**"
            - "windows/**"
            - ".github/workflows/docker.yml"
    workflow_dispatch:
    schedule:
        - cron: "17 3 1 * *"

permissions:
    contents: read

concurrency:
    group: docker-publish
    cancel-in-progress: false

jobs:
    publish:
        strategy:
            fail-fast: false
            matrix:
                variant:
                    - tag: latest
                      build_args: {}

        uses: Faulo/workflows-docker/.github/workflows/publish.yml@v1
        with:
            image: compose-unity
            tag: ${{matrix.variant.tag}}
            build_args: ${{toJSON(matrix.variant.build_args)}}
        secrets:
            DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
            DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
